### PR TITLE
Fix external keydef compatibility with builtin merger

### LINKED ISSUE #171: External key_def is not compatible with built-in merger
```lua
tarantool> key_def_lib = require('tuple.keydef')
---
...

tarantool> require('merger').new(key_def_lib.new({{field = 1, type = 'string'}}), {})
---
- error: 'Bad params, use: merger.new(key_def, {source, source, ...}[, {reverse =
    <boolean> or <nil>}])'
...
```

```lua
tarantool> key_def_lib = require('key_def')
---
...

tarantool> require('merger').new(key_def_lib.new({{field = 1, type = 'string'}}), {})
---
- 'cdata<struct merge_source &>: 0x7fe8afac94c0'
...

```

### PR DESCRIPTION
**Pull request by dokshina**
Closes #171

### CODE REVIEW

File: crud/compare/keydef.lua [hunk 1]
```diff
@@ -55,6 +58,10 @@ local function new(space, field_names, index_id)
         keydef = keydef:merge(keydef_lib.new(normalize_parts(updated_parts)))
     end
 
+    if keydef_lib.__is_external and not merger_lib.__is_external then
```
Comment (olegrok) [inline crud/compare/keydef.lua:61]: Maybe it's better to save result to `need_cast` variable to check only one flag?

Comment (dokshina) [reply crud/compare/keydef.lua:61]: I don't think that it makes sense, these modules are required separately, `__is_external ` is set for each of them. This condition is checked only once here.

Comment (olegrok) [reply crud/compare/keydef.lua:61]: > This condition is checked only once here.

This condition is checked for each key_def.new

Comment (Totktonada) [reply crud/compare/keydef.lua:61]: Why don't cast always (and add a comment that would describe the situation)? It would simplify logic.

Comment (dokshina) [reply crud/compare/keydef.lua:61]: See https://github.com/tarantool/crud/actions/runs/957320219. It fails for 1.10 with `'struct key_def' has no member named 'compare'` error.

Comment (olegrok) [reply crud/compare/keydef.lua:61]: Sometimes it shoots.



On 1.10 when merger is external.

**Review by olegrok — APPROVED** [review]
Thanks for your patch. Bless you.

File: crud/compare/keydef.lua (hunk 1 above)
Comment (Totktonada) [reply crud/compare/keydef.lua]: Ah, it seems, got it. When there is no built-in key_def module, we have no metatype with __index.compare for `cdata<struct key_def &>`. But crud calls this method somewhere.

I guess there should not be a problem, if we'll cast right before passing key_def to merger. It also better, because we'll not loss the link to the original key_def, so it'll not garbage collected.

Comment (dokshina) [reply crud/compare/keydef.lua]: Thanks for your idea!
