### PR TITLE
safe/fast mode: remove fiber kill

### LINKED ISSUE #473: Unsafe fiber termination by name causes killing unrelated fibers
After upgrading CRUD to 1.7.0, we observed unstable behavior on storage nodes when the expirationd role is enabled. During role application, the fiber executing apply() may be unexpectedly killed. This happens while CRUD is performing storage calls in “fast mode”. As a result, role application is interrupted and fail. The issue is caused by how CRUD currently identifies and terminates its internal fibers.

**Root cause**
CRUD relies on fiber.name() to identify internal “fast-mode” fibers and kills fibers by matching their name. This assumption is unsafe for several reasons:
 - changed fiber.name persists after crud request completed
 - As a result, a different, unrelated fiber may later be killed by crud

### PR DESCRIPTION
**Pull request by Satbek**
This pr improves performance of current crud operations and remove fiber killing in safe mode start. 

In this pr added:
- remove fiber killing on safe mode switch
- move safe mode switch from `on_commit` trigger to `on_replace` trigger
- crud methods run in safe mode for vinyl spaces

## remove fiber killing on safe mode switch 
In fast mode, every fiber was named **"fast"** so it could be killed when safe mode was enabled.

However, CRUD storage methods do not yield until a space operation is performed.  
The rebalancing trigger is executed on `insert`/`replace` into the `_bucket` space; this operation **does yield** and switches the implementation of the `bucket_ref` / `bucket_unref` functions.

Therefore, once a fiber starts in fast mode, it remains in fast mode until the first `box.space` operation:
- a **write** for memtx

As a result, there is no need to mark and kill iproto fibers that handle fast requests, because there is no situation in which a fiber remains in fast mode while rebalancing is in progress.

Yield checks were added to the tests (`yield_checks`) to ensure that no yields occur during these operations.

## move safe mode switch from `on_commit` to `on_replace` trigger

This change ensures that with turned on MVCC crud method will be executed on safe mode, when replace in `_bucket` space happened but not commited yet.

##  crud methods run in safe mode for vinyl spaces

vinyl can make more than one yield in box operation. So were made decision to run crud method for vinyl space always in 
safe mode.

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Closes #473

### CODE REVIEW

File: crud/delete.lua [hunk 1]
```diff
@@ -58,6 +62,8 @@ local function delete_on_storage(space_name, key, field_names, opts)
         fetch_latest_metadata = opts.fetch_latest_metadata,
     }, space, key)
 
+    finish()
```
Comment (vakhov) [inline crud/delete.lua]: if an unexpected Lua error is thrown between yield_checks.start() and finish() (for example, inside schema.wrap_func_result()), the fiber would remain registered in yield_checks.registry. could this potentially affect subsequent tests and lead to confusing errors?

File: crud/common/call.lua [hunk 2]
```diff
@@ -18,38 +16,13 @@ local CallError = errors.new_class('CallError')
...
 local CALL_FUNC_NAME = 'call_on_storage'
 local CRUD_CALL_FUNC_NAME = utils.get_storage_call(CALL_FUNC_NAME)
-local CRUD_CALL_FIBER_NAME = CRUD_CALL_FUNC_NAME .. '/fast'
 
 local call = {}
 
-local function call_on_storage_safe(run_as_user, func_name, ...)
+local function call_on_storage(run_as_user, func_name, ...)
     return box.session.su(run_as_user, call_cache.func_name_to_func(func_name), ...)
 end
```
[the remark this answers is not in the document]
Comment (Satbek) [reply crud/common/call.lua]: These are internal implementation details, and users do not need to be aware of them.

The API with subscriptions to rebalancing events remains unchanged, so I do not see a reason to explicitly document that some internal code was removed.

File: crud/common/schema.lua [hunk 3]
```diff
@@ -216,6 +217,8 @@ end
 -- `add_space_schema_hash` is true
 function schema.wrap_func_result(space, func, opts, ...)
     dev_checks('table', 'function', 'table')
+    yield_checks.check_no_yields()
```
Comment (a1div0) [inline crud/common/schema.lua]: Why do we check for no context switches **before** executing a user method?

File: crud/common/yield_checks.lua [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+	end
+	return res_err, ...
+end
+
+local function guard(f, ...)
+	register_fiber()
+	return finish(pcall(f, ...))
+end
+
+if os.getenv("TARANTOOL_CRUD_ENABLE_INTERNAL_CHECKS") == "ON" then
```
Comment (a1div0) [inline crud/common/yield_checks.lua]: Why do we enable functionality using an environment variable instead of a global setting?

Comment (ita-sammann) [inline crud/common/yield_checks.lua]: Why don't we add this var to the test environment by default?

[the remark this answers is not in the document]
Comment (Satbek) [reply crud/common/yield_checks.lua]: The variable is already set and value is "ON".

**Review by vakhov — APPROVED** [review]
