### PR TITLE
Fix passing timeout option for select/pairs

### LINKED ISSUE #209: Select/pairs error with using timeout
If I pass timeout as an option for select or pairs I get an error:

Select

```lua
    local crud = require('crud')

    local res, err = crud.select('customers', nil, {timeout = 1})
        
    if err ~= nil then
        return err
    end

    return nil
```

Pairs

```lua
    local crud = require('crud')

    local results = {}
    for _, result in crud.pairs('customers', nil, {timeout = 1}) do
        table.insert(results, result)
    end
        
    return results
```

Error:

```
.../crud/select/compat/select.lua:21: unexpected argument opts.timeout to func
```

### PR DESCRIPTION
**Pull request by AnaNek**
Before this patch passing `timeout` option to `crud.select()`/`crud.pairs()`
had been leading to an error `unexpected argument opts.timeout to func`.
Function `build_select_iterator` accepts `timeout` as a part of `call_opts`
table option. Before this patch function `build_select_iterator` had been
receiving `timeout` as a separate parameter which had been leading to a failure.

Closes #209

### CODE REVIEW

**Comment by mRrvz** [comment]
Please write in the description (and commit message) why these changes are needed.

File: test/integration/select_test.lua [hunk 1]
```diff
@@ -1508,3 +1508,41 @@ pgroup.test_jsonpath_index_field_pagination = function(g)
...
+        {4, 1161, "William", "White", 81, "Chicago"},
+    })
+    t.assert_equals(result.metadata, {
+        {name = 'id', type = 'unsigned'},
+        {name = 'bucket_id', type = 'unsigned'},
+        {name = 'name', type = 'string'},
+        {name = 'last_name', type = 'string'},
+        {name = 'age', type = 'number'},
+        {name = 'city', type = 'string'},
+    })
```
Comment (mRrvz) [inline test/integration/select_test.lua:1547]: Is this check really necessary? (metadata)

**Review by olegrok — APPROVED** [review]
Looks good after @mRrvz comments will be resolved.

File: test/integration/select_test.lua (hunk 1 above)
Comment (AnaNek) [reply test/integration/select_test.lua]: Removed.

**Review by Totktonada — APPROVED** [review]
On a brief glance it looks logical.

**Review by mRrvz — APPROVED** [review]

**Review by ligurio — APPROVED** [review]
