### PR TITLE
Bug: Collations

### LINKED ISSUE #22: [2pt] Bug: Collations
In Tarantool 1.10 conn.space contains collation ID instead of collation
Selecting by field w/ collations isn't tested properly now

### PR DESCRIPTION
**Pull request by dokshina**
Closes #22

### CODE REVIEW

File: test/unit/select_filters_test.lua [hunk 1]
```diff
@@ -311,7 +311,7 @@ g.test_unicode_collation = function()
             types = {'string', 'string', 'string', 'number'},
             early_exit_is_possible = false,
             values_opts = {
-                {collation='unicode_ci'},
+                {collation='unicode'},
                 {collation='unicode_ci'},
                 {collation='unicode_ci'},
```
Comment (olegrok) [inline test/unit/select_filters_test.lua:316]: Maybe here you could add "binary" and "none" collactions?

Comment (dokshina) [reply test/unit/select_filters_test.lua:316]: I would like to add one more test for this. It's too much for one test.

Comment (olegrok) [reply test/unit/select_filters_test.lua:316]: Sounds good

**Review by olegrok — APPROVED** [review]
