### PR TITLE
Fix case with invalid pagination

### LINKED ISSUE #137: CRUD parses composite index condition incorrectly when limit (opts.first) is set to 1.
It seems that CRUD interprets conditions incorrectly for composite keys when limit is set to 1.

### Space definition:
```lua

    --BookTranslation space
    local book_translation = box.schema.space.create(
            'book_translation',
            {
                format = {
                    { name = 'id', type = 'unsigned' },
                    { name = 'bucket_id', type = 'unsigned' },
                    { name = 'language', type = 'string' },
                    { name = 'edition', type = 'integer' },
                    { name = 'translator', type = 'string' },
                    { name = 'comments', type = 'string', is_nullable = true },
                },
                if_not_exists = true,
            }
    )

    book_translation:create_index('id', {
        parts = { 'id', 'language', 'edition' },
        if_not_exists = true,
    })

    book_translation:create_index('bucket_id', {
        parts = { 'bucket_id' },
        unique = false,
        if_not_exists = true,
    })

```

### Example of failing request:
```
localhost:3301> crud.select('book_translation')
---
- metadata: [{'name': 'id', 'type': 'unsigned'}, {'name': 'bucket_id', 'type': 'unsigned'},
    {'name': 'language', 'type': 'string'}, {'name': 'edition', 'type': 'integer'},
    {'name': 'translator', 'type': 'string'}, {'type': 'string', 'name': 'comments',
      'is_nullable': true}]
  rows:
  - [5, 17486, 'Ukrainian', 55, 'Mitro Dmitrienko', 'Translation 55']
...

localhost:3301>  crud.select('book_translation', {{'=','id',{5, 'Ukrainian', 55}}}, {first=2})
---
- metadata: [{'name': 'id', 'type': 'unsigned'}, {'name': 'bucket_id', 'type': 'unsigned'},
    {'name': 'language', 'type': 'string'}, {'name': 'edition', 'type': 'integer'},
    {'name': 'translator', 'type': 'string'}, {'type': 'string', 'name': 'comments',
      'is_nullable': true}]
  rows:
  - [5, 17486, 'Ukrainian', 55, 'Mitro Dmitrienko', 'Translation 55']
...

localhost:3301>  crud.select('book_translation', {{'=','id',{5, 'Ukrainian', 55}}}, {first=1})
---
- null
- line: 228
  class_name: SelectError
  err: '.../.rocks/share/tarantool/crud/select/type_comparators.lua:27: attempt to
    compare string with number'
  file: '...dge/.rocks/share/tarantool/crud/select/compat/select.lua'
  stack: "stack traceback:\n\t...dge/.rocks/share/tarantool/crud/select/compat/select.lua:228:
    in function <...dge/.rocks/share/tarantool/crud/select/compat/select.lua:175>\n\t[C]:
    in function 'xpcall'\n\t...st/resources/cartridge/.rocks/share/tarantool/errors.lua:145:
    in function <...st/resources/cartridge/.rocks/share/tarantool/errors.lua:139>\n\t[C]:
    in function 'pcall'\n\tbuiltin/box/console.lua:402: in function <builtin/box/console.lua:378>\n\t[C]:
    at 0x006093a0"
  str: 'SelectError: .../.rocks/share/tarantool/crud/select/type_comparators.lua:27:
    attempt to compare string with number'
...
```

### Additional debug information.

I traced CRUD code and found some details on error.
It seems that some index fields are compared with wrong fields (Language is compared to Edition).

```
testapp.s2-master | 2021-03-26 11:29:50.060 [14306] main/136/main type_comparators.lua:23 E> COMPARE DBG lhs=Ukrainian rhs=55 types: lhs=string, rhs=number
testapp.s2-master | 2021-03-26 11:29:50.060 [14306] main/136/main type_comparators.lua:25 E> Stack: stack traceback:
testapp.s2-master |     .../.rocks/share/tarantool/crud/select/type_comparators.lua:25: in function <.../.rocks/share/tarantool/crud/select/type_comparators.lua:21>
testapp.s2-master |     ...ridge/.rocks/share/tarantool/crud/select/comparators.lua:25: in function 'scan_comparator'
testapp.s2-master |     ...artridge/.rocks/share/tarantool/crud/select/executor.lua:65: in function 'execute'
testapp.s2-master |     ...sources/cartridge/.rocks/share/tarantool/crud/select.lua:69: in function <...sources/cartridge/.rocks/share/tarantool/crud/select.lua:38>
testapp.s2-master |     [C]: at 0x0060a030
```

### PR DESCRIPTION
**Pull request by olegrok**
This quite strange that it didn't shoot before.
However, we introduced a merger usage so behaviour was changed a
bit. So pagination over primary key were broken and this patch
fixes it and introduces test for it.

Closes #137

### CODE REVIEW

File: test/integration/select_test.lua [hunk 1]
```diff
@@ -610,6 +610,52 @@ pgroup:add('test_composite_index', function(g)
...
+            id = 5,
+            language = 'Ukrainian',
+            edition = 55,
+            translator = 'Mitro Dmitrienko',
+            comments = 'Translation 55',
+        }
+    })
+    t.assert_equals(#book_translation, 1)
+
+    local result, err = g.cluster.main_server.net_box:call('crud.select',
```
Comment (dokshina) [inline test/integration/select_test.lua:640]:
```
local conditions = {{'=', 'id', {5, 'Ukrainian', 55}}}

local result, err = g.cluster.main_server.net_box:call('crud.select', {'book_translation', conditions})
```

Comment (olegrok) [reply test/integration/select_test.lua]: Ok. Fixed

**Review by dokshina — APPROVED** [review]
Brilliant!
