### PR TITLE
Fixed select crash when dropping indexes.

### LINKED ISSUE #103: [1pt] Select could fail in case of sparsed indexes array
https://github.com/tarantool/crud/commit/e5eb7ca3076bd61451b5ceccd7338c07cc96351e#diff-8afead6b3cb6ef4117be97c1bf3ac723a454b7ddff094d300e42c20431b37bf0R42

A problem is following:
```lua
box.cfg{}
box.schema.space.create('space')
box.space.space:create_index('i1')
box.space.space:create_index('i2')
box.space.space:create_index('i3')
box.space.space:create_index('i4')
box.space.space.index.i2:drop()
box.space.space.index.i3:drop()

tarantool> #box.space.space.index  -- Ooops
---
- 0
...
tarantool> box.space.space.index[0]
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  type: TREE
  id: 0
  space_id: 512
  name: i1
...

tarantool> box.space.space.index[1]
---
- null
...

tarantool> box.space.space.index[2]
---
- null
...

tarantool> box.space.space.index[3]
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  id: 3
  type: TREE
  space_id: 512
  name: i4
...
```

Seems crud should consider it. See `table.maxn`

### PR DESCRIPTION
**Pull request by mRrvz**
Fixed selection error when dropping indexes by replacing the ``#`` operator with a call to ``table.maxn`` when creating a select plan.

Closes #103.

### CODE REVIEW

File: crud/select/plan.lua [hunk 1]
```diff
@@ -15,19 +15,23 @@ local function index_is_allowed(index)
 end
 
 local function get_index_for_condition(space_indexes, space_format, condition)
-    for i= 0, #space_indexes do
+    for i= 0, table.maxn(space_indexes) do
```
Comment (olegrok) [inline crud/select/plan.lua:18]: Hi! Thanks for your patch!

Could you move length calculation into separate variable that could be used here and below?
I'll place some benchmarks below. It's too expensive to call `table.maxn` twice.

Also could you add a space between "i" and "=" `i= 0` -> `i = 0` since you change this place?

```lua
local clock = require('clock')

local t = {}
for i = 1, 1e5 do
    t[i] = i
end

local s = clock.time()
local _
for _ = 1, 1e5 do
    _ = table.maxn(t)
end
print('maxn', clock.time() - s)

s = clock.time()

local _
for _ = 1, 1e5 do
    _ = #t
end
print('#', clock.time() - s)

-- tarantool test.lua 
-- maxn	6.1955099105835
-- #	0.012683868408203
```

Comment (olegrok) [reply crud/select/plan.lua:18]: However, my benchmark could be not relevant since amount of indexes is restricted with 65k:

For arrays with length ~1k table.maxn even faster than `#`. But anyway if we could call it only once we should do it.

File: test/unit/select_dropped_indexes_test.lua [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+
+    customers:create_index('name_tree', {
+        type = 'TREE',
+        parts = {'name'},
+        unique = false,
+        if_not_exists = true,
+    })
+
+    customers.index.name_hash:drop()
+    customers.index.age_hash:drop()
```
Comment (dokshina) [inline test/unit/select_dropped_indexes_test.lua:65]: You've copied this code from test that checks smth related to index type, thats why indexes are named `*_<hash,tree>`. But these tests aren't about it. I suggest naming indexes just `index1, index2, ...` because we want to test that removing index doesn't affect iterating over indexes, so these names are good IMHO.

Comment (dokshina) [reply test/unit/select_dropped_indexes_test.lua:65]: You can also name some of them `index_dropped` or smth like this.

File: test/unit/select_dropped_indexes_test.lua [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+
+    t.assert_equals(plan.conditions, conditions)
+    t.assert_equals(plan.space_name, 'customers')
+    t.assert_equals(plan.index_id, 2)
+    t.assert_equals(plan.scan_value, {20})
+    t.assert_equals(plan.after_tuple, nil)
+    t.assert_equals(plan.scan_condition_num, 1)
+    t.assert_equals(plan.iter, box.index.EQ)
+    t.assert_equals(plan.total_tuples_count, nil)
+    t.assert_equals(plan.sharding_key, nil)
```
Comment (dokshina) [inline test/unit/select_dropped_indexes_test.lua:99]: Maybe it's enough to check only these conditions:

```
 t.assert_equals(plan.conditions, conditions)
    t.assert_equals(plan.space_name, 'customers')
    t.assert_equals(plan.index_id, 2)
```

File: test/unit/select_dropped_indexes_test.lua [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+
+    customers:create_index('index6', {
+        type = 'TREE',
+        parts = {'name'},
+        unique = false,
+        if_not_exists = true,
+    })
+
+    customers.index.index_dropped1:drop()
+    customers.index.index_dropped2:drop()
```
Comment (olegrok) [inline test/unit/select_dropped_indexes_test.lua:65]: It would be great to add some check to show that `#customers.index == 3` but actually there are 4 indexes.

File: crud/select/plan.lua [hunk 5]
```diff
@@ -15,19 +15,24 @@ local function index_is_allowed(index)
 end
 
 local function get_index_for_condition(space_indexes, space_format, condition)
-    for i= 0, #space_indexes do
+    local maxn = table.maxn(space_indexes)
```
Comment (dokshina) [inline crud/select/plan.lua:18]: Please, add a comment why do we need `maxn` here.

Comment (dokshina) [reply crud/select/plan.lua:18]: And I don't sure that `maxn` is a good name for this variable.

File: test/unit/select_dropped_indexes_test.lua [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+    })
+
+    customers:create_index('index3', {
+        type = 'TREE',
+        parts = {'age'},
+        unique = false,
+        if_not_exists = true,
+    })
+
+    customers:create_index('index_dropped1', {
```
Comment (dokshina) [inline test/unit/select_dropped_indexes_test.lua:45]: A nit: maybe smth like `index4_dropped`?

File: test/unit/select_dropped_indexes_test.lua [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+    customers.index.index4_dropped:drop()
+    customers.index.index5_dropped:drop()
+end
+
+g.after_all = function()
+    box.space.customers:drop()
+end
+
+g.test_conditions = function()
+    t.assert(#box.space.customers.index ~= table.maxn(box.space.customers.index))
```
Comment (dokshina) [inline test/unit/select_dropped_indexes_test.lua:73]: I don't understand such test, @olegrok, was it your suggestion?

File: test/unit/select_dropped_indexes_test.lua [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+end
+
+g.test_dropped_index_call = function()
```
Comment (dokshina) [inline test/unit/select_dropped_indexes_test.lua:76]: This test checks what? That removing indexes works?)

File: test/unit/select_dropped_indexes_test.lua (hunk 7 above)
Comment (olegrok) [reply test/unit/select_dropped_indexes_test.lua:73]: yes, it was my suggestion

Comment (dokshina) [reply test/unit/select_dropped_indexes_test.lua:73]: I need a comment to understand why do we need such test.

Moreover, I sure that it shouldn't be a separated test. I think that such assertions should be performed for all test group (I mean `before_all` section), and should lead to fail of all group tests.

Comment (olegrok) [reply test/unit/select_dropped_indexes_test.lua:73]: My suggestion was just add a check. It's needed to check initial conditions correctness that test actually covers a problem. Yes, I agree that assert in before_all should be enough.

File: test/unit/select_dropped_indexes_test.lua [hunk 9]
```diff
@@ -63,24 +63,13 @@ g.before_all = function()
...
     customers.index.index4_dropped:drop()
     customers.index.index5_dropped:drop()
-end
-
-g.after_all = function()
-    box.space.customers:drop()
-end
 
-g.test_conditions = function()
+    -- We need this check to make sure that tests actually covers a problem.
```
Comment (olegrok) [inline test/unit/select_dropped_indexes_test.lua:67]: typo: `tests actually cover` (without "s").

**Comment by dokshina** [comment]
Thanks a lot for your patch! Please, update Changelog.

I would like you to make your comment about why do we use `table.maxn` more clear (probably add an example). And since we have 2 places where it's used, we need two comments. Think about people who will read this code sometimes - they should understand it without suffering.

**Review by dokshina — APPROVED** [review]
