### PR TITLE
fix compatibility with old Tarantool versions

### LINKED ISSUE #163: [2pt] Unable to use `crud.common.utils` on Tarantool 1.10.10 without `key_def` module
Cartridge role requires `crud.common.utils`

```
RegisterRoleError: .../.rocks/share/tarantool/crud/common/compat.lua:20: module 'key_def' not found:
```

### PR DESCRIPTION
**Pull request by olegrok**
After a15e77448a1c44a24e4842c5f2b6e4db6447ffd5 (Introduce crud.min and crud.max)
module started to throw an error
```
.../.rocks/share/tarantool/crud/common/compat.lua:20: module 'key_def' not found:
```

Because some 1.10 versions don't have support tuple-keydef module
or they didn't installed it near this module.
This patch adds a fix that fallbacks such lost souls to lua
implemented comparators.

Also 1.10.6 EE is added to test process to be able verify changes.

Closes #163

### CODE REVIEW

File: crud/borders.lua [hunk 1]
```diff
@@ -44,14 +45,25 @@ function borders.init()
    _G._crud.get_border_on_storage = get_border_on_storage
 end
 
-local function is_closer(compare_sign, keydef, tuple, res_tuple)
-    if res_tuple == nil then
-        return true
-    end
+local is_closer
+
+if has_keydef then
```
Comment (dokshina) [inline crud/borders.lua:50]: I sure that it should be encapsulated in compare.keydef.I mean, using comparators instead of keydef.

Comment (olegrok) [reply crud/borders.lua:50]: Oh, no

Comment (olegrok) [reply crud/borders.lua:50]: It's just bugfix for annoying refactoring create a separate issue and take it to sprint.

File: CMakeLists.txt [hunk 2]
```diff
@@ -31,6 +31,9 @@ install(
 
 # Don't include to rockspec as some Tarantool versions (e.g. 2.2 and 2.3)
 # don't have symbols required by "tuple-merger" and "tuple-keydef" modules.
+execute_process(
+    COMMAND bash "-c" "tarantoolctl rocks install tuple-keydef 0.0.2"
+)
```
Comment (mRrvz) [inline CMakeLists.txt:36]: Please, add newline after this line, like in lines above

Comment (olegrok) [reply CMakeLists.txt:36]: Done

File: crud/borders.lua (hunk 1 above)
Comment (no1seman) [reply crud/borders.lua:50]: There is another solution: simply include tuple_keydef to sdk: https://github.com/tarantool/sdk/pull/210

Comment (olegrok) [reply crud/borders.lua:50]: > There is another solution: simply include tuple_keydef to sdk: [tarantool/sdk#210](https://github.com/tarantool/sdk/pull/210)

It's not a solution at all. Because there are some Tarantool versions that does not support tuple-keydef/tuple-merger modules.

**Review by dokshina — APPROVED** [review]
Please, update CHANGELOG

File: crud/borders.lua (hunk 1 above)
Comment (olegrok) [reply crud/borders.lua:50]: > File an issue please.

https://github.com/tarantool/crud/issues/168

**Comment by olegrok** [comment]
> Please, update CHANGELOG

Done. https://github.com/tarantool/crud/compare/ce369c7d1ede31d11102354b5f12114a85e792ba..18cf1bbfeb9e7e9abfaf38533a7269c1a56afbc0
