### PR TITLE
schema: fix stale schema for metadata generation

### LINKED ISSUE #236: crud.update() may use stale schema for metadata generation
We can change existing test to reveal the problem.

```diff
diff --git a/test/integration/simple_operations_test.lua b/test/integration/simple_operations_test.lua
index 8c33daa..45041ae 100644
--- a/test/integration/simple_operations_test.lua
+++ b/test/integration/simple_operations_test.lua
@@ -396,14 +396,14 @@ end
 
 pgroup.test_intermediate_nullable_fields_update = function(g)
     local result, err = g.cluster.main_server.net_box:call(
-        'crud.insert', {'developers', {1, box.NULL}})
+        'crud.insert', {'developers', {3, box.NULL}})
     t.assert_equals(err, nil)
 
     local objects = crud.unflatten_rows(result.rows, result.metadata)
     t.assert_equals(objects, {
         {
-            id = 1,
-            bucket_id = 477
+            id = 3,
+            bucket_id = 2804
         }
     })
 
@@ -414,19 +414,22 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
     end)
 
     local result, err = g.cluster.main_server.net_box:call('crud.update',
-        {'developers', 1, {{'=', 'extra_3', { a = { b = {} } } }}})
+        {'developers', 3, {{'=', 'extra_3', { a = { b = {} } } }}})
     t.assert_equals(err, nil)
     objects = crud.unflatten_rows(result.rows, result.metadata)
     t.assert_equals(objects, {
         {
-            id = 1,
-            bucket_id = 477,
+            id = 3,
+            bucket_id = 2804,
             extra_1 = box.NULL,
             extra_2 = box.NULL,
             extra_3 = {a = {b = {}}},
         }
     })
 
+    -- Temporary disabled
+    --[[
+
     -- Test uses jsonpaths so it should be run for version 2.3+
     -- where jsonpaths are supported (https://github.com/tarantool/tarantool/issues/1261).
     -- However since 2.8 Tarantool could update intermediate nullable fields
@@ -486,6 +489,8 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
             extra_12 = 'extra_value_12'
         }
     })
+
+    ]]-- Temporary disabled
 end
 
 pgroup.test_object_with_nullable_fields = function(g)
```

This patch does not change meaning of the test, just changes storage replicaset to work with.

After this, the test fails:

```lua
$ luatest -v -p test_intermediate_nullable_fields_update
<...>
    simple_operations.engine:"memtx".test_intermediate_nullable_fields_update ... (0.058s) fail
...ol-meta/crud/test/integration/simple_operations_test.lua:420: expected: 
{
    {
        bucket_id = 2804,
        extra_1 = cdata<void *>: NULL,
        extra_2 = cdata<void *>: NULL,
        extra_3 = {a = {b = {}}},
        id = 3,
    },
}
actual: 
{{bucket_id = 2804, id = 3}}
<...>
```

I looked at the problem a bit and my draft of the fix is the following:

```diff
diff --git a/crud/update.lua b/crud/update.lua
index 587068c..2942e76 100644
--- a/crud/update.lua
+++ b/crud/update.lua
@@ -103,6 +103,18 @@ local function call_update_on_router(space_name, key, user_operations, opts)
     end
 
     local bucket_id = sharding.key_get_bucket_id(sharding_key, opts.bucket_id)
+
+    -- We should use a space object from the same connection as
+    -- we use for the request itself. Otherwise we can use a stale
+    -- format to generate rows metadata.
+    --
+    -- XXX: This fix is fast written and may have problems. IOW, I
+    -- didn't think much about it.
+    space, err = utils.get_space(space_name, {vshard.router.route(bucket_id)})
+    if err ~= nil then
+        return nil, UpdateError:new("Failed to get space %q: %s", space_name, err), true
+    end
+
     local call_opts = {
         mode = 'write',
         timeout = opts.timeout,
```

Of course, we should look, whether it is fully correct: we use a space format from a 'wrong' connection before this code and, maybe, it should be revisited too.

I would also verify other operations for problems of this kind.

### PR DESCRIPTION
**Pull request by GRISHNOV**
Corrects using of an stale schema to generate metadata during `crud.update`, `crud.insert`, `crud.insert_*`, `crud.replace`, `crud.replace_*`, `crud.upsert`, `crud.upsert_*`, `crud.delete`, `crud.max`, `crud.min`, `crud.select`,`crud.pairs`, `crud.get` working.

If the implemented `fetch_latest_metadata` option is used, it is guaranteed that the metadata will be up-to-date. Before receiving the space format, a mismatch check will be performed between the scheme version on all involved storage and the scheme version in the net_box connection of the router. In case of mismatch, the schema reload will be triggered.

- [x] Tests
- [x] Changelog
- [x] Documentation

Related with #361 
Closes #236

### CODE REVIEW

File: test/integration/simple_operations_test.lua [hunk 1]
```diff
@@ -490,6 +490,34 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
     })
 end
 
+pgroup.test_gh_236_update_with_actual_metadata = function(g)
```
Comment (DifferentialOrange) [inline test/integration/simple_operations_test.lua:493]: Actually, this test doesn't verify anything. I've tried to revert the changes above and it had succeeded. I assume that Alexander example had relied on some schema migration in previous test and we need to replicate it here.

Comment (GRISHNOV) [reply test/integration/simple_operations_test.lua]: Fixed: modified `test_intermediate_nullable_fields_update`, now this draft version not reproduce on `master`

Comment (DifferentialOrange) [reply test/integration/simple_operations_test.lua]: Well, it isn't nice. Now tests rely on the order and shuffle can change their logic. Moreover, now basic behavior tests also check non-basic case, and it won't be clear for anyone who will read this test suite without the commit history. Let's try to make a full reproducer in a separate single test, I don't think it would be too hard.

Comment (DifferentialOrange) [reply test/integration/simple_operations_test.lua]: It's okay if it would also result in subsequent cases fail before the patch

Comment (GRISHNOV) [reply test/integration/simple_operations_test.lua]: Done

**Review by DifferentialOrange — COMMENTED** [review]
Thank you for finding the issue. Let's just fail on each schema mismatch and pass the reload procedure to the existing wrapper.

**Comment by DifferentialOrange** [comment]
You'll also need to update this developer's doc: https://github.com/tarantool/crud/blob/master/doc/dev/schema.md

File: CHANGELOG.md [hunk 2]
```diff
@@ -14,6 +14,10 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
   `upsert`, `upsert_object`, `upsert_many`, `upsert_object_many`,
   `update`, `delete`. (#267).
 
+### Fixed
```
Comment (DifferentialOrange) [inline CHANGELOG.md:17]: `bugfix:` in a commit message is not a module subsystem. Use `schema:` or something like this instead

File: crud/insert.lua [hunk 3]
```diff
@@ -121,6 +122,13 @@ local function call_insert_on_router(vshard_router, space_name, original_tuple,
         end
 
         return nil, err_wrapped
+    else
+        if schema.result_needs_reload(space, storage_result) then
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/insert.lua:126]: Did I understand the idea correctly?

```lua
local err_wrapped = InsertError:new("Failed to insert: %s", storage_result.err)

if schema.result_needs_reload(space, storage_result) then
    return nil, err_wrapped, const.NEED_SCHEMA_RELOAD
end

if storage_result.err ~= nil then
    return nil, err_wrapped
end
```

Code above causes a duplicate key error, since, as I understand it, the `insert` triggered several times in `schema.wrap_func_reload`

[the remark this answers is not in the document]
Comment (DifferentialOrange) [reply crud/insert.lua:126]: > Code above causes a duplicate key error

Let's check schema before actual storage operation

File: test/integration/simple_operations_test.lua [hunk 4]
```diff
@@ -490,6 +490,193 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
...
+            need_pre_insert_data = true,
+        },
+        crud_select = {
+            operation_name = 'crud.select',
+            input = {'countries', {}, {fetch_latest_metadata = true}},
+            need_pre_insert_data = true,
+        },
+    }
+
+    for case_name, case in pairs(cases) do
```
Comment (DifferentialOrange) [inline test/integration/simple_operations_test.lua:647]: Can you organize it to have a separate case for each operation?

For example, like here
https://github.com/tarantool/crud/blob/781ef16fc3ab725cf4c0720b9f67def80b32f785/test/integration/stats_test.lua#L591-L598

File: test/integration/simple_operations_test.lua [hunk 5]
```diff
@@ -490,6 +490,193 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
...
+        local result, err = g.cluster.main_server.net_box:call(
```
Comment (DifferentialOrange) [inline test/integration/simple_operations_test.lua:648]: The test is dishonest here.

1. We create a space with schema version one.
2. Optionally, we insert some data.
3. We perform a migration to schema version two.
4. We perform a crud operation which reloads schema and returns latest metadata.

Any case that happens after the first one already works with schema version two connections and doesn't reload. To make test cases really test migration, we must do something like the following.


1. We drop the space.
2. We create a space with schema version one.
3. We perform some operation to fetch current schema.
4. Optionally, we insert some data.
5. We perform a migration to schema version two.
6. We perform a crud operation which reloads schema and returns latest metadata.

After implementing, we also should try to revert the changes and ensure that tests fail if we do not perform the reload.

**Review by DifferentialOrange — COMMENTED** [review]
Thank you for your patch! Mostly fine, but let's try to rework some things if pit doesn't seems too time-consuming.

File: crud/delete.lua [hunk 6]
```diff
@@ -145,6 +150,35 @@ local function call_delete_on_router(vshard_router, space_name, key, opts)
 
     local tuple = storage_result.res
 
+    if opts.fetch_latest_metadata == true then
+        -- The second request of the space is necessary to actualize the metadata of the DML operation.
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/delete.lua:154]: In the case of an operation that does not use `call.map` (`delete`, `update`, ...), we make a second `get_space` request. And if a mistmatch in the schema version is found after this, we `reload_schema`. 

In the case of `call.map` (`insert_many`, `select`, ...), we do not do the second `get_space`, but we check whether there is a mistmatch in the scheme version at least on one of the storages relative to the router, and if so, we  `reload_schema`

File: README.md [hunk 7]
```diff
@@ -236,6 +236,10 @@ where:
     the sole responsibility of the developer
   * `noreturn` (`?boolean`) - suppress successfully processed tuple
     (first return value is `nil`). `false` by default
+  * `fetch_latest_metadata` (`?boolean`) - guarantees the
+    up-to-date metadata (space format) in first return value, otherwise 
+    it may not take into account the latest migration of the data format. 
+    Using this option reduces performance by ~15 percent. `false` by default
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply README.md]: Done

File: crud/borders.lua [hunk 8]
```diff
@@ -35,10 +36,17 @@ local function get_border_on_storage(border_name, space_name, index_id, field_na
...
     end
 
-    return schema.wrap_func_result(space, get_index_border, {index}, {
+    local res, err = schema.wrap_func_result(space, get_index_border, {index}, {
         add_space_schema_hash = true,
         field_names = field_names,
     })
+
+    local replica_schema_version
+    if fetch_latest_metadata == true then
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/borders.lua:46]: Done

File: crud/borders.lua [hunk 9]
```diff
@@ -35,10 +36,17 @@ local function get_border_on_storage(border_name, space_name, index_id, field_na
...
+        replica_schema_version = box.internal.schema_version()
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/borders.lua]: Done

File: crud/delete.lua (hunk 6 above)
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/delete.lua]: Done, description corrected

File: crud/insert.lua [hunk 10]
```diff
@@ -1,6 +1,7 @@
 local checks = require('checks')
 local errors = require('errors')
 
+local log = require('log')
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/insert.lua]: Done

File: test/integration/simple_operations_test.lua (hunk 5 above)
Comment (GRISHNOV) [reply test/integration/simple_operations_test.lua]: Implemented `test_gh_236_dml_operation_return_actual_metadata_*` and `test_gh_236_dml_operation_return_outdated_metadata_without_bugfix_*`

File: test/integration/simple_operations_test.lua [hunk 11]
```diff
@@ -490,6 +490,207 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
...
+        for _, v in pairs(result.metadata) do
+            if v.name == gh_236_metadata_field_name[case_name] then
+                found_extra_field = true
+            end
+        end
+        t.assert_equals(found_extra_field, true,
+            string.format('cannot find the expected metadata for case: %s',
+                          case.operation_name))
+
+        helpers.call_on_servers(g.cluster, {'s1-master', 's2-master'},
```
Comment (DifferentialOrange) [inline test/integration/simple_operations_test.lua:687]: Move this one to `after_test` hook so there won't be any cascade fails.

File: README.md [hunk 12]
```diff
@@ -630,10 +654,14 @@ where:
     [sequence](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema_sequence/create_index/).
     **Warning**: there is no native support for sequences in sharded systems
     since each replicaset has its own sequence. If sequence field is a part
-    of the sharding key (which is true by default), choosing the bucket id is
+    of the sharding key (which is true by default), choosing the bucket id isPerformance overhead is up to 15%. `false` by default
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply README.md]: Fixed

File: crud/common/utils.lua [hunk 13]
```diff
@@ -158,6 +179,72 @@ function utils.get_space_format(space_name, vshard_router)
     return space_format
 end
 
+function utils.fetch_latest_metadata_when_single_storage(space, space_name, vshard_router, opts, storage_result)
+    -- The second get of the space is necessary to actualize the metadata of the DML operation.
+    -- This approach is temporary and is related to [1], [2].
+    -- [1] https://github.com/tarantool/crud/issues/236
+    -- [2] https://github.com/tarantool/crud/issues/361
+    local latest_space, err, netbox_schema_version = utils.get_space(space_name, vshard_router,
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/utils.lua]: Done

File: crud/common/utils.lua [hunk 14]
```diff
@@ -158,6 +179,72 @@ function utils.get_space_format(space_name, vshard_router)
...
+                                                                    opts.timeout, storage_result.replica_uuid)
+    if err ~= nil then
+        local warn_msg = "Failed to fetch space for latest schema actualization, metadata may be outdated: %s"
+        log.warn(warn_msg, err)
+    end
+    if latest_space == nil then
+        log.warn("Failed to find space for latest schema actualization, metadata may be outdated")
+    end
+    if storage_result.replica_schema_version ~= netbox_schema_version then
+        local warn_msg = "Replica with UUID %s actual schema version and net_box schema version has mismatch: " ..
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/utils.lua]: Done, deleted

File: crud/common/utils.lua [hunk 15]
```diff
@@ -158,6 +179,72 @@ function utils.get_space_format(space_name, vshard_router)
...
+    -- [2] https://github.com/tarantool/crud/issues/361
+    for storage_uuid, storage_info in pairs(storages_info) do
+        if storage_info.replica_schema_version ~= netbox_schema_version then
+            local warn_msg =
+                "Replica with UUID %s actual schema version and net_box schema version has mismatch: " ..
+                "actual replica schema version: %s; net_box conn schema version to this replica: %s. " ..
+                "Trying to reload schema"
+            log.warn(warn_msg, storage_uuid,
+                     storage_info.replica_schema_version, netbox_schema_version)
+            local ok, reload_schema_err = schema.reload_schema(vshard_router)
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/utils.lua:223]: Done, using `break`

File: crud/borders.lua (hunk 8 above)
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/borders.lua]: Done

File: crud/common/stash.lua [hunk 16]
```diff
@@ -20,12 +20,20 @@ local stash = {}
...
+-- @tfield string select_module_compat_info
+--  Stash for select compatability version registry.
+--
 stash.name = {
     cfg = '__crud_cfg',
     stats_internal = '__crud_stats_internal',
     stats_local_registry = '__crud_stats_local_registry',
     stats_metrics_registry = '__crud_stats_metrics_registry',
     ddl_triggers = '__crud_ddl_spaces_triggers',
+    storages_info_on_select = '__storages_info_on_select',
```
Comment (DifferentialOrange) [inline crud/common/stash.lua:35]: Why we adding new sections to stash?

File: crud/select/compat/select.lua [hunk 17]
```diff
@@ -336,8 +341,46 @@ local function select_module_call_xc(vshard_router, space_name, user_conditions,
...
+    if opts.fetch_latest_metadata then
+        -- Checking the relevance of the schema version is necessary
+        -- to prevent the irrelevant metadata of the DML operation.
+        -- This approach is temporary and is related to [1], [2].
+        -- [1] https://github.com/tarantool/crud/issues/236
+        -- [2] https://github.com/tarantool/crud/issues/361
+        local storages_info = stash.get(stash.name.storages_info_on_select)
+        for storage_uuid, storage_info in pairs(storages_info) do
+            if storage_info.replica_schema_version ~= iter.netbox_schema_version then
+                local warn_msg =
```
Comment (DifferentialOrange) [inline crud/select/compat/select.lua:353]: We decided not to warn if mismatch.

Comment (GRISHNOV) [reply crud/select/compat/select.lua]: Done

File: crud/common/stash.lua (hunk 16 above)
Comment (GRISHNOV) [reply crud/common/stash.lua]: Deleted, done via `fiber storage` for merger and `iter.storages_info` for old_select

File: crud/select/compat/select.lua [hunk 18]
```diff
@@ -336,8 +341,46 @@ local function select_module_call_xc(vshard_router, space_name, user_conditions,
         utils.reverse_inplace(tuples)
     end
 
+    if opts.fetch_latest_metadata then
+        -- Checking the relevance of the schema version is necessary
+        -- to prevent the irrelevant metadata of the DML operation.
+        -- This approach is temporary and is related to [1], [2].
+        -- [1] https://github.com/tarantool/crud/issues/236
+        -- [2] https://github.com/tarantool/crud/issues/361
+        local storages_info = stash.get(stash.name.storages_info_on_select)
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/select/compat/select.lua]: Done, deleted

File: crud/common/map_call_cases/batch_postprocessor.lua [hunk 19]
```diff
@@ -39,6 +39,11 @@ function BatchPostprocessor:collect(result_info, err_info)
         wrapper_args = '?table',
     })
 
+    if result_info.value ~= nil then
+        self.storage_info[result_info.key] = {}
+        self.storage_info[result_info.key].replica_schema_version = result_info.value[3]
```
Comment (DifferentialOrange) [inline crud/common/map_call_cases/batch_postprocessor.lua:44]: Why not perform it in a single step?

Comment (GRISHNOV) [reply crud/common/map_call_cases/batch_postprocessor.lua:44]: AFAIU, need to create table on key with uuid=`result_info.key`, else without it:

```lua
crud/common/map_call_cases/batch_postprocessor.lua:44: attempt to index a nil value
```

Comment (GRISHNOV) [reply crud/common/map_call_cases/batch_postprocessor.lua]: Done

File: crud/common/utils.lua [hunk 20]
```diff
@@ -158,6 +179,120 @@ function utils.get_space_format(space_name, vshard_router)
...
+           'check the replica_uuid value from storage ' ..
+           'for correct use of the fetch_latest_metadata opt')
+    assert(netbox_schema_version ~= nil,
+           'check the netbox_schema_version value from net_box conn on router ' ..
+           'for correct use of the fetch_latest_metadata opt')
+    if storage_result.replica_schema_version ~= netbox_schema_version then
+        local ok, reload_schema_err = schema.reload_schema(vshard_router)
+        if ok then
+            latest_space, err = utils.get_space(space_name, vshard_router,
+                                              opts.timeout, storage_result.replica_uuid)
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/utils.lua]: Done

File: test/integration/simple_operations_test.lua [hunk 21]
```diff
@@ -490,6 +490,213 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
...
+    -- [1] https://github.com/tarantool/crud/issues/236
+    -- [2] https://github.com/tarantool/crud/issues/361
+
+    local test_name = ('test_gh_236_dml_operation_return_actual_metadata_%s'):format(case_name)
+
+    pgroup.before_test(test_name, gh_236_case_prepare)
+    pgroup[test_name] = function(g)
+        local result, err
+
+        result, err = g.cluster.main_server.net_box:call(
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply test/integration/simple_operations_test.lua:674]: Added

File: doc/dev/schema.md [hunk 22]
```diff
@@ -92,6 +92,9 @@ Retry with reload is triggered
   - ``bucket_id`` calculation has failed due to any reason;
   - if updating by field name is not supported natively and id resolve
     has failed;
+- conditionally if the flag `fetch_latest_metadata` for DML operation that return metadata is used.
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply doc/dev/schema.md]: Done, moved

File: CHANGELOG.md [hunk 23]
```diff
@@ -14,6 +14,9 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
+* Crud DML operations was returning stale schema for metadata generation (#236).
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply CHANGELOG.md]: Done

File: crud/common/map_call_cases/base_postprocessor.lua [hunk 24]
```diff
@@ -52,6 +53,17 @@ function BasePostprocessor:collect(result_info, err_info)
         wrapper_args = '?table',
     })
 
+    if result_info.value ~= nil and type(result_info.value[1]) == 'table' then
+        self.storage_info[result_info.key] = {}
+        local replica_schema_version
+        if result_info.value[1].storage_info ~= nil then
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/map_call_cases/base_postprocessor.lua]: Done, simplified

File: crud/common/utils.lua [hunk 25]
```diff
@@ -158,6 +179,120 @@ function utils.get_space_format(space_name, vshard_router)
...
 
+function utils.fetch_latest_metadata_when_single_storage(space, space_name, netbox_schema_version,
+                                                         vshard_router, opts, storage_result)
+    -- Checking the relevance of the schema version is necessary
+    -- to prevent the irrelevant metadata of the DML operation.
+    -- This approach is temporary and is related to [1], [2].
+    -- [1] https://github.com/tarantool/crud/issues/236
+    -- [2] https://github.com/tarantool/crud/issues/361
+    local latest_space, err
+    assert(storage_result.replica_schema_version ~= nil,
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply crud/common/utils.lua]: Done, not changed

File: test/integration/simple_operations_test.lua [hunk 26]
```diff
@@ -490,6 +490,241 @@ pgroup.test_intermediate_nullable_fields_update = function(g)
...
+        need_pre_insert_data = true,
+    },
+    crud_select = {
+        operation_name = 'crud.select',
+        input = {'countries', {}, {fetch_latest_metadata = true}},
+        need_pre_insert_data = true,
+    },
+    crud_pairs = {
+        operation_name = 'crud.pairs',
+        input = { --[[ hardcoded insede eval --]] },
```
Comment (DifferentialOrange) [inline test/integration/simple_operations_test.lua:639]: Please, fix typo

File: doc/dev/schema.md [hunk 27]
```diff
@@ -92,6 +93,8 @@ Retry with reload is triggered
   - ``bucket_id`` calculation has failed due to any reason;
   - if updating by field name is not supported natively and id resolve
     has failed;
+  If there is a mismatch between the schema version on all involved storage
```
Comment (DifferentialOrange) [inline doc/dev/schema.md:96]: The bullet list is broken here

File: test/integration/simple_operations_test.lua (hunk 26 above)
Comment (GRISHNOV) [reply test/integration/simple_operations_test.lua]: Sorry, fixed

File: doc/dev/schema.md (hunk 27 above)
Comment (GRISHNOV) [reply doc/dev/schema.md]: Done, deleted
