### PR TITLE
Fix select by fully specified sharding key

### LINKED ISSUE #89: select: multipart index scan
Consider the case

primary key:  
  - x: integer
  - y: integer

put objects:
- [0, 1]
- [0, 2]
- [1, 2]

selects:
- box.select({0}) — returns [0, 1], [0, 2]
- crud.select({'=', 'primary', {0}}) — returns [0, 1]

tests related #88

### PR DESCRIPTION
**Pull request by dokshina**
Thanks @filonenko-mikhail for #88.

- [x] Tests
- [x] Changelog

Closes #89

### CODE REVIEW

File: crud/select/plan.lua [hunk 1]
```diff
@@ -165,7 +165,9 @@ function select_plan.new(space, conditions, opts)
     -- get sharding key value
     local sharding_key
     if scan_value ~= nil and (scan_iter == box.index.EQ or scan_iter == box.index.REQ) then
-        sharding_key = extract_sharding_key_from_scan_key(scan_value, scan_index, sharding_index)
+        if #scan_value == #scan_index.parts then
```
Comment (olegrok) [inline crud/select/plan.lua:168]: Why do you add new nesting level. Seems you can specify this condition at previous line.

**Comment by olegrok** [comment]
`eq conditin` -> `eq condition`

`only ne tuple` -> `only one tuple`

Please add dots after each sentence.

`Before length of primary key value in eq conditin wasn't checked to detect if fully sharding key is specified`

Not sure it's correct sentence.
`Before this patch a length of primary key for EQ conditions ...` seems it sounds better.

File: test/entrypoint/srv_select.lua [hunk 2]
```diff
@@ -57,6 +57,25 @@ package.preload['customers-storage'] = function()
...
+                if_not_exists = true,
+                engine = engine,
+            })
+            -- primary index
+            coord_space:create_index('primary', {
+                parts = { {field = 'x'}, {field = 'y'} },
+                if_not_exists = true,
+            })
+            coord_space:create_index('bucket_id', {
+                                         parts = { {field = 'bucket_id'} },
```
Comment (olegrok) [inline test/entrypoint/srv_select.lua:76]: broken indents

File: test/unit/select_plan_test.lua [hunk 3]
```diff
@@ -44,6 +44,25 @@ g.before_all = function()
...
+    -- is used for multipart primary index tests
+    local coord_space = box.schema.space.create('coord', {
+        format = {
+              {name = 'x', type = 'unsigned'},
+              {name = 'y', type = 'unsigned'},
+              {name = 'bucket_id', type = 'unsigned'},
+        },
+        if_not_exists = true,
+    })
+    --primary index
```
Comment (olegrok) [inline test/unit/select_plan_test.lua:57]: Here you add a space between "--" and "sentence" (https://github.com/tarantool/crud/pull/90/files#diff-3861a09acb51bc4ef85b8766f9a3a12b055062cb9c8a7fdedface313354d5ccaR27) why don't you do it for this line?

File: test/unit/select_plan_test.lua [hunk 4]
```diff
@@ -44,6 +44,25 @@ g.before_all = function()
...
+    coord_space:create_index('primary', {
+        parts = { {field = 'x'}, {field = 'y'} },
+        if_not_exists = true,
+    })
+    coord_space:create_index('bucket_id', {
+                                 parts = { {field = 'bucket_id'} },
```
Comment (olegrok) [inline test/unit/select_plan_test.lua:63]: broken indents

File: test/helper.lua [hunk 5]
```diff
@@ -76,4 +80,29 @@ function helpers.box_cfg()
...
+        local objects, err = crud.unflatten_rows(result.rows, result.metadata)
+        t.assert_equals(err, nil)
+        t.assert_equals(#objects, 1)
+        table.insert(inserted_objects, objects[1])
+    end
+
+    return inserted_objects
+end
+
+function helpers.get_by_idxs(objects, idxs)
```
Comment (olegrok) [inline test/helper.lua:100]: get_fields_by_index?

I don't understand what returns get_by_idxs function from its name.

**Review by olegrok — APPROVED** [review]

File: crud/select/plan.lua [hunk 6]
```diff
@@ -53,9 +53,10 @@ local function validate_conditions(conditions, space_indexes, space_format)
     return true
 end
 
+
```
Comment (olegrok) [inline crud/select/plan.lua:56]: Usually we keep only one line between functions. Why do you add this empty line?

**Review by olegrok — APPROVED** [review]
