### PR TITLE
utils: implement flatten function using codegeneration

### LINKED ISSUE #119: Error on insert_object/upsert_object when object has missing fields: 'Tuple/Key must be MsgPack array'
Attaching router logs to observe the error. As you can see after flatten (search  'CRUD DEBUG INSERT TUPLE' ) the resulting lua table does not contain all indexes of a valid array.

<details>
<summary>
Logs
</summary>

testserver.router | 2021-02-12 17:21:21.155 [199195] main/128/main insert.lua:131 E> CRUD DEBUG INSERT OBJ: {{ 
testserver.router | ["offer_status_cd"] = OfferStatus.ACTIVE,
testserver.router | ["control_group_cd"] = ControlGroupCd.CG,
testserver.router | ["mdm_customer_id"] = mdmCustomerId,
testserver.router | ["create_dttm"] = 5,
testserver.router | ["processed_dttm"] = 10,
testserver.router | ["offer_type_cd"] = OfferTypeCd.INFO,
testserver.router | ["offer_id"] = offerId1,
testserver.router | ["offer_issue_cd"] = OfferIssue.ONLINE,
testserver.router | ["source_system_cd"] = sourceSystemCd,
testserver.router | ["_class"] = io.tarantool.tester.CdOffer,
testserver.router | } }
testserver.router | 2021-02-12 17:21:21.155 [199195] main/128/main insert.lua:133 E> CRUD DEBUG INSERT FORMAT: {{ 
testserver.router | [1] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = bucket_id,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [2] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = offer_id,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [3] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = offer_desc,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [4] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = create_dttm,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [5] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = start_dttm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [6] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = end_dttm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [7] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = fact_end_dttm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [8] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = offer_type_cd,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [9] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = offer_status_cd,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [10] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = cim_lead_key_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [11] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = cim_communication_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [12] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = cim_communication_nm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [13] = { 
testserver.router | ["type"] = integer,
testserver.router | ["name"] = rto_contact_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [14] = { 
testserver.router | ["type"] = integer,
testserver.router | ["name"] = rto_cell_package_sk,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [15] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = rto_cell_package_nm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [16] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = source_system_cd,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [17] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = mdm_customer_id,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [18] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = risk_offer_matrix_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [19] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = risk_offer_matrix_dttm,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [20] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = offer_issue_cd,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [21] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = control_group_cd,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | [22] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = pilot_flg,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [23] = { 
testserver.router | ["type"] = integer,
testserver.router | ["name"] = comm_offer_priority_num,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [24] = { 
testserver.router | ["type"] = integer,
testserver.router | ["name"] = comm_offer_tendency_num,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [25] = { 
testserver.router | ["type"] = integer,
testserver.router | ["name"] = comm_variant_priority_num,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [26] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_online_view_flg,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [27] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_online_template_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [28] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_front_view_flg,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [29] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_front_template_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [30] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_atm_view_flg,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [31] = { 
testserver.router | ["type"] = string,
testserver.router | ["name"] = comm_atm_template_id,
testserver.router | ["is_nullable"] = true,
testserver.router | } ,
testserver.router | [32] = { 
testserver.router | ["type"] = unsigned,
testserver.router | ["name"] = processed_dttm,
testserver.router | ["is_nullable"] = false,
testserver.router | } ,
testserver.router | } }
testserver.router | 2021-02-12 17:21:21.156 [199195] main/128/main insert.lua:140 E> CRUD DEBUG INSERT TUPLE: {{ 
testserver.router | [2] = offerId1,
testserver.router | [4] = 5,
testserver.router | [8] = OfferTypeCd.INFO,
testserver.router | [9] = OfferStatus.ACTIVE,
testserver.router | [16] = sourceSystemCd,
testserver.router | [17] = mdmCustomerId,
testserver.router | [20] = OfferIssue.ONLINE,
testserver.router | [21] = ControlGroupCd.CG,
testserver.router | [32] = 10,
testserver.router | } }
testserver.router | 2021-02-12 17:21:21.157 [199195] main/128/main I>  after crud.insert_object, err:Insert: Failed to insert: Call: Failed for 99a45190-3ad7-4d04-855a-43977e3623bd: Function returned an error: {"code":32,"base_type":"ClientError","type":"ClientError","message":"Tuple\/Key must be MsgPack array","trace":[{"file":"[C]","line":4294967295}]}
testserver.router | stack traceback:
testserver.router |     ...r/testserver/.rocks/share/tarantool/crud/common/call.lua:163: in function 'rw_single'
testserver.router |     ...server/testserver/.rocks/share/tarantool/crud/insert.lua:72: in function 'insert_object'
testserver.router |     ...ata-tarantool-server/testserver/app/roles/api_router.lua:52: in function <...ata-tarantool-server/testserver/app/roles/api_router.lua:50>
testserver.router |     [C]: at 0x00608f60, entity: {"offer_status_cd":"OfferStatus.ACTIVE","control_group_cd":"ControlGroupCd.CG","mdm_customer_id":"mdmCustomerId","create_dttm":5,"processed_dttm":10,"offer_type_cd":"OfferTypeCd.INFO","offer_id":"offerId1","offer_issue_cd":"OfferIssue.ONLINE","source_system_cd":"sourceSystemCd","_class":"io.tarantool.tester.CdOffer"}

</details>

This patch fixes the issue:
```lua

function utils.flatten(object, space_format, bucket_id)
    if object == nil then return nil end

    local tuple = {}

    for fieldno, field_format in ipairs(space_format) do
        local value = object[field_format.name]

        if not system_fields[field_format.name] then
            if not field_format.is_nullable and value == nil then
                return nil, FlattenError:new("Field %q isn't nullable", field_format.name)
            end
        end

        if bucket_id ~= nil and field_format.name == 'bucket_id' then
            value = bucket_id
        end

-        tuple[fieldno] = value
+        tuple[fieldno] = value or box.NULL
    end

    return tuple
end
```

### PR DESCRIPTION
**Pull request by olegrok**
This patch introduces new approach to "flatten" function. Before
thus patch we dynamically process every object using cycles,
temporary tables, etc.

This patch implements "flatten" function using codegeneration.
No temporary tables, no redundant loops, simple linear code that
just assign input object fields to corresponding tuple fields.
My simple benchmarks (8 fields + bucket_id) show that this
implementation at least 3 times faster than previous.

Example of code is following:
```lua
local object, bucket_id = ...
for k in pairs(object) do
    if fieldmap[k] == nil then
        return nil, format('Unknown field %q is specified', k)
    end
end
local result = {NULL,NULL,NULL,NULL,}
if object["id"] == nil then
    return nil, 'Field "id" isn\'t nullable'
end
result[1] = object["id"]
if bucket_id ~= nil then
    result[2] = bucket_id
else
    result[2] = object["bucket_id"]
end
if object["name"] == nil then
    return nil, 'Field "name" isn\'t nullable'
end
result[3] = object["name"]
result[4] = object["age"]
return result
```

Closes #119

### CODE REVIEW

**Comment by vrogach2020** [comment]
This will probably fix https://github.com/tarantool/crud/issues/119

**Comment by olegrok** [comment]
> This will probably fix #119

It looks so. I'll probably should add a test for your issue.

**Comment by olegrok** [comment]
> This will probably fix #119

No. It didn't fix your problem. But I improved my patch - https://github.com/tarantool/crud/pull/115/commits/d006e19a63e37d4469dea1583a69f294b7a9bbc0. Currently it fixes serialization issue.

**Review by vrogach2020 — COMMENTED** [review]
Nice implementation. Please see my comment on cache.

File: crud/common/utils.lua [hunk 1]
```diff
@@ -52,40 +52,70 @@ function utils.get_space_format(space_name, replicasets)
...
+        fieldmap = fieldmap,
+        NULL = box.NULL,
+    }
+    fun = assert(load(code, '@flatten', 't', env))
 
-    for fieldname in pairs(object) do
-        if not fieldnames[fieldname] then
-            return nil, FlattenError:new("Unknown field %q is specified", fieldname)
-        end
+    cache[space_format] = fun
```
[the remark this answers is not in the document]
Comment (olegrok) [reply crud/common/utils.lua:114]: No. Here we use lua [weak tables](https://www.lua.org/pil/17.html).

There is two details is important here:
  - We use "space_format" as a key. If it is changed we create new function for new format.
  - We use weak table as a cache. When there are no any references to space format (it happens when format is changed) function is GCed.

File: crud/common/utils.lua [hunk 2]
```diff
@@ -52,40 +52,71 @@ function utils.get_space_format(space_name, replicasets)
...
-local system_fields = { bucket_id = true }
+local function put(lines, s, ...)
+    table.insert(lines, string.format(s, ...))
+end
+
+local cache = setmetatable({}, {__mode = 'k'})
 
 function utils.flatten(object, space_format, bucket_id)
-    if object == nil then return nil end
+    local fun = cache[space_format]
```
Comment (dokshina) [inline crud/common/utils.lua:62]: `cache` -> `flatten_functions_cache`?

Comment (dokshina) [reply crud/common/utils.lua:62]: `fun` is used for `luafun`, I think it's better to use `flatten_func` name.

File: crud/common/utils.lua [hunk 3]
```diff
@@ -52,40 +52,71 @@ function utils.get_space_format(space_name, replicasets)
     return space_format
 end
 
-local system_fields = { bucket_id = true }
+local function put(lines, s, ...)
```
Comment (dokshina) [inline crud/common/utils.lua:55]: `put` what and where? 
Maybe `append`?

File: test/integration/simple_operations_test.lua [hunk 4]
```diff
@@ -391,3 +391,114 @@ pgroup:add('test_upsert', function(g)
...
+            is_sweet = box.NULL,
+            is_useful = box.NULL,
+            is_yellow = box.NULL,
+        }
+    })
+
+    local _
+    -- Upsert: first is insert then update
+    -- {3, 2804, NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL}
+    _, err = g.cluster.main_server.net_box:call(
```
Comment (dokshina) [inline test/integration/simple_operations_test.lua:470]: Why not `local _, err`?

Comment (olegrok) [reply test/integration/simple_operations_test.lua:470]: AFAIU our linter settings is quite dehumanized and prohibits variable redefinition.

Comment (dokshina) [reply test/integration/simple_operations_test.lua:470]: No, it allows variable redefinition and it is used everywhere in tests.

File: crud/common/utils.lua (hunk 3 above)
Comment (olegrok) [reply crud/common/utils.lua]: np

File: crud/common/utils.lua (hunk 2 above)
Comment (olegrok) [reply crud/common/utils.lua]: > cache -> flatten_functions_cache?

ok

> fun is used for luafun, I think it's better to use flatten_func name.

ok

File: test/integration/simple_operations_test.lua (hunk 4 above)
Comment (olegrok) [reply test/integration/simple_operations_test.lua]: Well, fixed

**Review by dokshina — APPROVED** [review]
Thanks for your patch!

Please, update Changelog and feel free to merge.
