### PR TITLE
Bug: Equal Condition

### LINKED ISSUE #23: [2pt] Bug: Select with equal conditions
* Tuple comparator should use scan key merged w/ primary key
* Comparator operator should be one of > or < for tuples sorting
* Seems that every select by equal condition is interpreted as a select with a fully specified sharding key

### PR DESCRIPTION
**Pull request by dokshina**
Closes #23

### CODE REVIEW

File: crud/select/comparators.lua [hunk 1]
```diff
@@ -150,6 +150,15 @@ local function gen_array_cmp_func(target, key_parts)
     end
 end
 
+local cmp_operators_by_tarantool_iter = {
```
Comment (olegrok) [inline crud/select/comparators.lua:153]: Please add a comment with description. At first glance I don't understand why it's needed

File: crud/select/comparators.lua [hunk 2]
```diff
@@ -158,23 +167,29 @@ local array_cmp_funcs_by_operators = {
...
+    assert(cmp_operator ~= nil, 'Unknown Tarantool iterator %q', tarantool_iter)
+
+    return cmp_operator
+end
 
+function comparators.gen_func(cmp_operator, key_parts)
+    local cmp_func = array_cmp_funcs_by_operators[cmp_operator]
     if cmp_func == nil then
-        return nil, ComparatorsError:new('Unsupported operator %q', operator)
+        return nil, ComparatorsError:new('Unsupported operator %q', cmp_operator)
```
Comment (olegrok) [inline crud/select/comparators.lua:180]: Still I'm sure "Unsupported" and "Unknown" iterators should be splitted

File: crud/select/comparators.lua (hunk 1 above)
Comment (dokshina) [reply crud/select/comparators.lua:153]: Added a comment to `comparators.get_cmp_operator` function.

File: crud/select/comparators.lua (hunk 2 above)
Comment (dokshina) [reply crud/select/comparators.lua:186]: It's not a check that iterator isn't exists, it's an only check that it can be used for tuples comparator, so it's `Unsupported`.

**Review by olegrok — APPROVED** [review]
