### PR TITLE
Fix pagination + multipart indexes

### LINKED ISSUE #170: [8pt] Pagination [+ multipart indexes] is broken
Following tests should be fixed https://github.com/tarantool/crud/pull/169/files#diff-6ea5935828108f3cd61997766f7c37952a79debc13a01a31a4c168ed343c843f

### PR DESCRIPTION
**Pull request by mRrvz**
Fixed invalid results for pagination queries when filtering on
a parts of a composite index. Now, instead of "scrolling" 
to the desired tuple (during pagination) using the 
``scroll_to_after_tuple`` function, we change the iterators 
(``EQ`` -> ``GE``, ``REQ`` -> ``LT``) to use them in 
``index:pairs`` function, together with a combination with 
additional filtration. Closes #170

### CODE REVIEW

File: crud/select/executor.lua [hunk 1]
```diff
@@ -83,6 +83,16 @@ function executor.execute(space, index, filter_func, opts)
...
 
+    if opts.after_tuple ~= nil then
+        if opts.tarantool_iter == box.index.LE then
+            opts.tarantool_iter = box.index.LT
+        elseif opts.tarantool_iter == box.index.EQ then
+            opts.tarantool_iter = box.index.GE
+        elseif opts.tarantool_iter == box.index.REQ then
+            opts.tarantool_iter = box.index.LT
+        end
+    end
```
Comment (olegrok) [inline crud/select/executor.lua:94]: I think it could be moved to the plan

File: crud/select/filters.lua [hunk 2]
```diff
@@ -649,11 +666,13 @@ function filters.gen_func(space, conditions, opts)
     dev_checks('table', '?table', {
         tarantool_iter = 'number',
         scan_condition_num = '?number',
+        after_tuple = '?table',
```
Comment (olegrok) [inline crud/select/filters.lua:669]: I don't see any usages. Is it really needed?

File: crud/select/filters.lua [hunk 3]
```diff
@@ -649,11 +666,13 @@ function filters.gen_func(space, conditions, opts)
...
     })
 
     local filter_conditions, err = parse(space, conditions, {
         scan_condition_num = opts.scan_condition_num,
         tarantool_iter = opts.tarantool_iter,
+        after_tuple = opts.after_tuple,
```
Comment (olegrok) [inline crud/select/filters.lua:675]: I don't see any usages. Is it really needed?

File: crud/select/filters.lua (hunk 2 above)
Comment (olegrok) [reply crud/select/filters.lua:669]: My bad. It's used.

File: crud/select/filters.lua [hunk 4]
```diff
@@ -95,6 +96,22 @@ local function parse(space, conditions, opts)
     end
 
     local filter_conditions = {}
+
+    if opts.after_tuple ~= nil and #conditions > 0 then
+        if opts.tarantool_iter == box.index.EQ or opts.tarantool_iter == box.index.REQ then
+            local index = space_indexes[conditions[1].operand]
```
Comment (olegrok) [inline crud/select/filters.lua:102]: I think it should be `opts.scan_condition_num` not just `1`.

**Review by ligurio — CHANGES_REQUESTED** [review]
@mRrvz Alexey, thanks for the patch!

Few comments:

- could you add explanations to commit messages "Fix unnecessary sharding key", "Remove unnecessary test". For me it is not clear what was fixed regarding to sharding key and why we need to remove test.
- I suppose the item to changelog should be added in the same commit where fix was added.

File: crud/select/plan.lua [hunk 5]
```diff
@@ -208,7 +208,7 @@ function select_plan.new(space, conditions, opts)
 
     -- get sharding key value
     local sharding_key
-    if scan_value ~= nil and (scan_iter == box.index.EQ or scan_iter == box.index.REQ) then
+    if scan_value ~= nil and scan_after_tuple == nil and (scan_iter == box.index.EQ or scan_iter == box.index.REQ) then
```
Comment (olegrok) [inline crud/select/plan.lua:211]: Why?

It seems only first query could be executed on single shard if full sharding key is specified.

File: crud/select/filters.lua (hunk 4 above)
Comment (olegrok) [reply crud/select/filters.lua:102]: Or plan contains index id. It could be also used.

File: crud/select/executor.lua (hunk 1 above)
Comment (dokshina) [reply crud/select/executor.lua:94]: I was sure that we already have such code in the plan...

Comment (olegrok) [reply crud/select/executor.lua:94]: > I was sure that we already have such code in the plan...

We have only pain

File: crud/select/plan.lua [hunk 6]
```diff
@@ -206,6 +212,16 @@ function select_plan.new(space, conditions, opts)
...
 
+    if scan_after_tuple ~= nil then
+        if scan_iter == box.index.LE then
+            scan_iter = box.index.LT
+        elseif scan_iter == box.index.EQ then
+            scan_iter = box.index.GE
+        elseif scan_iter == box.index.REQ then
+            scan_iter = box.index.LT
+        end
+    end
```
Comment (olegrok) [inline crud/select/plan.lua:223]: nit: I think this change should be done before `local sharding_index = primary_index` line. 

`local sharding_index = primary_index` and `local sharding_key ...` are in "sharding" group of code.

File: crud/select/plan.lua [hunk 7]
```diff
@@ -182,6 +182,12 @@ function select_plan.new(space, conditions, opts)
         return nil, err
     end
 
+    if scan_after_tuple ~= nil then
+        if scan_iter == box.index.REQ or scan_iter == box.index.EQ then
+            table.insert(conditions, conditions[scan_condition_num])
+        end
+    end
```
Comment (olegrok) [inline crud/select/plan.lua:189]: Patch is more laconic and it's great but this change is not trivial. Please put a comment here.

File: test/unit/select_plan_test.lua [hunk 8]
```diff
@@ -256,7 +256,7 @@ g.test_first = function()
     t.assert_equals(plan.scan_value, {777}) -- after_tuple id
     t.assert_equals(plan.after_tuple, after_tuple)
     t.assert_equals(plan.scan_condition_num, nil)
-    t.assert_equals(plan.tarantool_iter, box.index.LE) -- inverted iterator
+    t.assert_equals(plan.tarantool_iter, box.index.LT) -- inverted iterator
```
Comment (olegrok) [inline test/unit/select_plan_test.lua:259]: Maybe it worth to add more unit test that shows that EQ iterator is changed to GT if after tuple is passed?

File: crud/select/plan.lua [hunk 9]
```diff
@@ -182,6 +182,18 @@ function select_plan.new(space, conditions, opts)
         return nil, err
     end
 
+    -- We duplicate this condition so that it works in `filters.gen_func`
+    -- (see function `parse`) - therefore it does not process `conditions`
+    -- (and not converted them to `filtter_conditions` array) with an array
```
Comment (olegrok) [inline crud/select/plan.lua:187]: `filtter_conditions` -> `filter_conditions `

File: crud/select/plan.lua [hunk 10]
```diff
@@ -182,6 +182,18 @@ function select_plan.new(space, conditions, opts)
...
+    -- index equal to opts.scan_condition_num. This condition, together with
+    -- the cobination "inversion" of the scan iterator (see lines below),
+    -- is needed for correct pagination when using a partial index.
```
Comment (olegrok) [inline crud/select/plan.lua:190]: To be honest I don't understand it.

I think that:
```
Since we use pagination we should continue iteration since after tuple.
Such iterator could be run only with index:pairs(key(after_tuple), 'GT/LT').
To preserve original condition we should manually inject it in filter_conditions
(see ...).
```

I think also we can't use "inversion" term for iterator. Inversion is transformation LT -> GT, GE -> LE, but here it is changed just to continue iterator in direct and reverse order.

**Review by olegrok — APPROVED** [review]
Thanks for your patch. Please resolve the rest of not my comments.

File: CHANGELOG.md [hunk 11]
```diff
@@ -7,6 +7,10 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ## [Unreleased]
 
+### Fixed
+
+* Pagination with composite indexes
```
Comment (dokshina) [inline CHANGELOG.md:12]: Please describe a kind of error. It wasn't working at all? Or bad result was returned?

**Review by dokshina — APPROVED** [review]
Please make Changelog more informative.

**Comment by dokshina** [comment]
> @mRrvz Alexey, thanks for the patch!
> 
> Few comments:
> 
> * could you add explanations to commit messages "Fix unnecessary sharding key", "Remove unnecessary test". For me it is not clear what was fixed regarding to sharding key and why we need to remove test.
> * I suppose the item to changelog should be added in the same commit where fix was added.

.

**Review by ligurio — CHANGES_REQUESTED** [review]

**Review by ligurio — APPROVED** [review]

**Review by dokshina — APPROVED** [review]
